name: gcpdefunctions

channels:
- conda-forge
- defaults
dependencies:
- python>=3.8
- chardet==4.0.0
- openpyxl==3.0.9
- pandas==1.3.1
- protobuf==3.19.4
- pymongo==4.0.1
- pytz==2021.1
- requests==2.25.1
- numpy==1.18.5
- tqdm ==4.61.2
- patool==1.12

pip:
  - sendgrid==6.9.6
  - office365==0.3.15
  - Office365_REST_Python_Client==2.2.1

 
