name: GCP_data_eng_functions
channels:
- conda-forge
- defaults
dependencies:
- python>=3.8
- chardet==4.0.0
- openpyxl==3.0.9
- pandas==1.3.1
- protobuf==3.19.4
- pymongo==4.0.1
- pytz==2021.1
- requests==2.25.1
- tqdm==4.61.2
- patool==1.12
pip:
  - sendgrid==6.9.6
  - office365==0.3.15
  - office365_rest_python_client==2.2.1
